/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { SyncSwapClassicPool__factory } from "./SyncSwapClassicPool__factory";
export { SyncSwapClassicPoolFactory__factory } from "./SyncSwapClassicPoolFactory__factory";
