/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IStakingPool,
  IStakingPoolInterface,
} from "../../../contracts/interfaces/IStakingPool";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "onBehalf",
        type: "address",
      },
    ],
    name: "stake",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IStakingPool__factory {
  static readonly abi = _abi;
  static createInterface(): IStakingPoolInterface {
    return new utils.Interface(_abi) as IStakingPoolInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IStakingPool {
    return new Contract(address, _abi, signerOrProvider) as IStakingPool;
  }
}
