/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC20__factory } from "./ERC20__factory";
export { ERC20Readonly__factory } from "./ERC20Readonly__factory";
export { ERC20WithPermit__factory } from "./ERC20WithPermit__factory";
