/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20 } from "./ERC20";
export type { ERC20Readonly } from "./ERC20Readonly";
export type { ERC20WithPermit } from "./ERC20WithPermit";
