/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SyncSwapStablePool } from "./SyncSwapStablePool";
export type { SyncSwapStablePoolFactory } from "./SyncSwapStablePoolFactory";
