/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IFeeRegistry,
  IFeeRegistryInterface,
} from "../../../../contracts/interfaces/master/IFeeRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "isFeeSender",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IFeeRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IFeeRegistryInterface {
    return new utils.Interface(_abi) as IFeeRegistryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFeeRegistry {
    return new Contract(address, _abi, signerOrProvider) as IFeeRegistry;
  }
}
