/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IFeeRecipient,
  IFeeRecipientInterface,
} from "../../../../contracts/interfaces/master/IFeeRecipient";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint16",
        name: "feeType",
        type: "uint16",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "feeRate",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "notifyFees",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IFeeRecipient__factory {
  static readonly abi = _abi;
  static createInterface(): IFeeRecipientInterface {
    return new utils.Interface(_abi) as IFeeRecipientInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFeeRecipient {
    return new Contract(address, _abi, signerOrProvider) as IFeeRecipient;
  }
}
