/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IForwarderRegistry,
  IForwarderRegistryInterface,
} from "../../../../contracts/interfaces/master/IForwarderRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "forwarder",
        type: "address",
      },
    ],
    name: "isForwarder",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IForwarderRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IForwarderRegistryInterface {
    return new utils.Interface(_abi) as IForwarderRegistryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IForwarderRegistry {
    return new Contract(address, _abi, signerOrProvider) as IForwarderRegistry;
  }
}
