/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as classic from "./classic";
export type { classic };
import type * as stable from "./stable";
export type { stable };
export type { BasePoolFactory } from "./BasePoolFactory";
