/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { SyncSwapStablePool__factory } from "./SyncSwapStablePool__factory";
export { SyncSwapStablePoolFactory__factory } from "./SyncSwapStablePoolFactory__factory";
