/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20 from "./ERC20";
export type { erc20 };
import type * as erc3156 from "./ERC3156";
export type { erc3156 };
import type * as factory from "./factory";
export type { factory };
import type * as master from "./master";
export type { master };
import type * as pool from "./pool";
export type { pool };
import type * as protocol from "./protocol";
export type { protocol };
import type * as token from "./token";
export type { token };
import type * as vault from "./vault";
export type { vault };
export type { ICallback } from "./ICallback";
export type { IStakingPool } from "./IStakingPool";
export type { IWETH } from "./IWETH";
