/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBasePoolFactory } from "./IBasePoolFactory";
export type { IPoolFactory } from "./IPoolFactory";
