/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20 } from "./IERC20";
export type { IERC20Balance } from "./IERC20Balance";
export type { IERC20Metadata } from "./IERC20Metadata";
export type { IERC20Permit } from "./IERC20Permit";
export type { IERC20WithMetadata } from "./IERC20WithMetadata";
export type { IERC20WithPermit } from "./IERC20WithPermit";
