/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC3156FlashBorrower } from "./IERC3156FlashBorrower";
export type { IERC3156FlashLender } from "./IERC3156FlashLender";
export type { IFlashLoan } from "./IFlashLoan";
export type { IFlashLoanRecipient } from "./IFlashLoanRecipient";
export type { IVault } from "./IVault";
