/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC165 } from "./IERC165";
export type { IERC20 } from "./IERC20";
export type { IERC20Base } from "./IERC20Base";
export type { IERC20Permit } from "./IERC20Permit";
export type { IERC20Permit2 } from "./IERC20Permit2";
export type { IERC20PermitAllowed } from "./IERC20PermitAllowed";
