/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as uniswap from "./uniswap";
export type { uniswap };
export type { ISyncSwapFactory } from "./ISyncSwapFactory";
export type { ISyncSwapPair } from "./ISyncSwapPair";
