/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { SyncSwapFactory__factory } from "./SyncSwapFactory__factory";
export { SyncSwapPair__factory } from "./SyncSwapPair__factory";
